src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap, src/ui/Onboarding/index.js
=> chore: Capitalized Bulleted List Items in Onboarding Process

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore: Adds Pull Request Template

src/live/LiveButton.js, src/tabs/home/Features/index.js
This PR comments/removes tracking in feed features and the live bar so that we make sure links work correctly. Added TODO's so that we can come back and make this work later.
Open the Sim and make sure the links in the feed features (Staff Block, etc.) work correctly.
**Manual QA**
---
=> fix: Removed Tracking to Correct Links

src/prayer/data/queries/getCampusPrayers.js, src/prayer/data/queries/getGroupPrayers.js, src/prayer/data/queries/getPrayers.js
This adds a necessary field in the queries for the save button to work properly.
Play around with saving and unsaving prayers. Make sure it's consistent and nothing looks out of place.
**Manual QA**
---
=> fix: Fixes saving inconsistencies

src/index.js
We don't need to be sending *all* the navigation parameters, it's breaking the `track` functions.
Pull up a network inspector and confirm clicking around in prayer isn't generating any track mutation failures (413 errors)
**Manual QA**
---
=> fix: Fixes Analytics mutations

schema.graphql, src/bugsnag.js, src/index.js
=> chore: Adds store to bugsnag reports

__mocks__/react-native-permissions/index.js, apollos.json, ios/Podfile, ios/Podfile.lock, package.json, src/tabs/connect/RecentlyLikedTileFeed/RecentlyLikedTileFeed.js, src/tabs/connect/getUserProfile.js, src/tabs/discover/DiscoverFeed/TileContentFeed.js, src/tabs/home/Home.js, src/ui/BrandedCard.js, src/user-settings/Locations/Marker.js, src/user-settings/getUserPhoto.js, src/user-settings/uploadPhoto.js, yarn.lock
=> chore: Beta Release

.travis.yml, CHANGELOG.md, package.json, yarn.lock
This gives us fancy Github releases where normal people can go see what changed.
Can't really
**Manual QA**
---
=> chore: Adds Github releases

package.json
Adds a helper script `yarn restart` for a commonly used pattern to start fresh.
**Manual QA**
---
=> chore: Adds a restart command

src/index.js
Adds AppCenter crash data for us to analyze. May be better ¯\\\_(ツ)\_/¯
**Manual QA**
---
=> chore: Adds Appcenter crash reports

.travis.yml, CHANGELOG.md, package.json, src/index.js, yarn.lock
=> Beta Release

ios/Podfile.lock, package.json, yarn.lock
=> fix: Fixes Videos...Again

src/tabs/connect/index.js, src/ui/LikedContentFeedConnected.js
This PR fixes the cards on the liked content feed.
**Manual QA**
---
=> fix: Fix the liked content feed

src/tabs/home/Home.js
This PR fixes the campaign card so that it shows the correct UI when we're live.
Pull up the home feed when we're live and make sure that the UI is correct.
**Manual QA**
---
=> fix: Fixes the UI on the campaign card when we're live

schema.graphql, src/prayer/PrayerSingle/index.js, src/prayer/UserPrayerList/UserPrayerList.tests.js, src/prayer/UserPrayerList/__snapshots__/UserPrayerList.tests.js.snap, src/prayer/UserPrayerList/index.js, src/prayer/data/queries/getPrayerFeed.js
This PR updates user prayers to be paginated. 
Create a whole bunch of prayers in `alpha-rock` for yourself, run the app against that database and see that it paginates correctly.
**Manual QA**
---
=> chore: Paginated User Prayers

schema.graphql
=> chore: Updates Local Schema

schema.graphql, src/content-single/Features/NoteFeature.js, src/content-single/Features/SermonNotes/index.js, src/content-single/Features/TextFeature.js
Gives us analytics on:
- exporting Sermon notes
- clicking fill in the blanks
- adding custom notes
Only way would be to boot the app in release mode and then look for the event in AppCenter.
**Manual QA**
---
=> chore: Adds Sermon Notes Analytics

schema.graphql, src/content-single/HTMLContent/index.js
Finally gives us info on content with bad image URLs
Go to a piece of content with a bad image.
**Manual QA**
---
=> chore: Adds Bad image info

.travis.yml, package.json, scripts/bump-version-code.sh
Fixes the Travis config script (I hope)
No idea
**Manual QA**
---
=> chore: Fixes auto-versioning

package.json, yarn.lock
Fixes the browser so that it opens the in-app browser or external browser correctly.
Run through the links on the Connect tab (or any link) and make sure it opens in the correct browser (in-app or external)
**Manual QA**
---
=> fix: Browser opens external links correctly

.travis.yml, CHANGELOG.md, android/app/build.gradle.bak, ios/newspringchurchapp-tvOS/Info.plist, ios/newspringchurchapp-tvOSTests/Info.plist, ios/newspringchurchapp.xcodeproj/project.pbxproj, ios/newspringchurchapp/Info.plist, ios/newspringchurchappTests/Info.plist, package.json
=> Develop to Master

.eslintrc.js, e2e/config.json, e2e/firstTest.spec.js, e2e/init.js, package.json, yarn.lock
Gives us the ability to start adding detox tests.
`yarn detox test`
It will be fail but it's a start. For us to do anything useful, we'll need to add hooks to the core buttons inside the onboarding package.
**Manual QA**
---
=> chore: Adds scaffold for detox integration testing

README.md
=> chore: Added Instructions to Readme

src/Providers.js, src/analytics/index.js, src/content-single/Features/NoteFeature.js, src/content-single/Features/SermonNotes/index.js, src/content-single/Features/TextFeature.js, src/index.js, src/ui/LiveButton.js, src/ui/MediaControls.js
Moves Appcenter analytics calls to the same place to make tracking both easier.
Click something and watch it appear in Appcenter.
**Manual QA**
---
=> chore: Moved Appcenter Analytics

src/content-single/DevotionalContentItem/__snapshots__/Devotional.tests.js.snap, src/prayer/AddPrayer/WithYou/__snapshots__/WithYou.tests.js.snap, src/tabs/discover/DiscoverFeed/__snapshots__/DiscoverFeed.tests.js.snap, src/tabs/discover/__snapshots__/discover.tests.js.snap, src/theme/theme.js, src/ui/Onboarding/__snapshots__/Onboarding.tests.js.snap
This PR makes our links have more contrast.
The links should have a heavier font-weight.
**Manual QA**
---
=> chore: Better Links

schema.graphql
=> chore: Updates Schema

.github/workflows/tests.yml
=> chore: Uses Yarn for Tests

schema.graphql
This PR updates the local schema with changes from crete.
**Manual QA**
---
=> chore: Update Schema

schema.graphql, src/prayer/ActionComponent.js, src/prayer/AnswerPrayerForm/AnswerPrayerForm.js, src/prayer/AnswerPrayerForm/AnswerPrayerForm.tests.js, src/prayer/AnswerPrayerForm/AnswerPrayerFormConnected.js, src/prayer/AnswerPrayerForm/AnswerPrayerFormConnected.tests.js, src/prayer/AnswerPrayerForm/__snapshots__/AnswerPrayerForm.tests.js.snap, src/prayer/AnswerPrayerForm/__snapshots__/AnswerPrayerFormConnected.tests.js.snap, src/prayer/AnswerPrayerForm/index.js, src/prayer/PrayerSingle/PrayerSingle.tests.js, src/prayer/PrayerSingle/__snapshots__/PrayerSingle.tests.js.snap, src/prayer/PrayerSingle/index.js, src/prayer/UserPrayerList/UserPrayerList.tests.js, src/prayer/UserPrayerList/index.js, src/prayer/data/fragments/prayerFragment.js, src/prayer/data/mutations/answerPrayer.js, src/tabs/prayer/index.js, src/theme/icons/Ellipsis.js, src/theme/icons/index.js
This PR makes it possible for a person to enter an answer to their prayer.
Lots of changes here:
* Changed the `My Prayers` card to show the `ellipsis` icon instead of the trash can. 
* Changed the `My Prayers` card to show the answer to the prayer if there is one.
* Changed the action menu to show "Mark as Answered" if the prayer doesn't have an answer and "Edit Answer" if it does.
* Added a new screen that the person would use to enter in their answer.
* We no longer regard a prayers expiration date on the `My Prayers` (USER) prayer feed. We show all the prayers a person has entered in most recent first order. 
* Prayers with answers, regardless of expiration date should not show in the regular prayer feeds. The exception is the `My Saved Prayers` feed. If you've saved a prayer and it …
=> feat: Answered Prayer

schema.graphql, src/tabs/connect/ActionBar.js
Adds back in the check-in to people in the test group
Just pull up the connect tab
**Manual QA**
---
=> chore: Adds Experimental Check In Feature

src/bugsnag.js
=> chore: Logs Error Response

src/NavigationService.js, src/Providers.js, src/ui/Onboarding/index.js, src/ui/Onboarding/onboardingStatus.js
=> fix: Use local storage and a user id to only onboard once

README.md
Just updated the instructions for new version numbers, read it over and see if it makes sense to you.
**Manual QA**
---
=> chore: Update Release Process Instructions

src/tabs/home/Home.js, src/tabs/home/__snapshots__/home.tests.js.snap
Fixes loading state
Manually set to `true`
**Manual QA**
---
=> fix: Fixes Android Campaign Loading State

appcenter-post-clone.sh
=> chore: Fixes Appcenter Builds

.github/workflows/jest.yml, .github/workflows/lint.yml
This is what we did for crete. I think it more quickly tells us what's broken which I like.
merge it :)
**Manual QA**
---
=> chore: Breaks Out CI Tests

src/tabs/connect/ActionBar.js
This will give us analytics events for clicking the giving and groups buttons.
click them and watch them pop up in amplitude
**Manual QA**
---
=> chore: Track Giving and Groups Clicks

ios/Info.plist, ios/Podfile, ios/Podfile.lock, ios/newspringchurchapp.xcodeproj/project.pbxproj, schema.graphql
This PR removes the Bluetooth requirement for the `react-native-google-cast` library. This is in an effort to stop getting this warning from App Store Connect:
`ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer …
=> fix: Removed the Bluetooth Requirement for Chromecast

src/ui/HorizontalContentSeriesFeedConnected.js
This is honestly just a guess but I bet it's boucing between the loading state.
Do a combination of different sermon series and studies, loading and cached.
**Manual QA**
---
=> fix: Fixes Bouncy Series Label

src/index.js
Makes Google Cast experimental only until we can figure out what's wrong.
Log in as you, then as someone else. Should disappear.
**Manual QA**
---
=> chore: Makes Google Cast Experimental

loadConfig.js
Adds "Studies" to devotional series items in the home feed.
Boot up the sim.
**Manual QA**
---
=> chore: Adds Pills to Studies

src/client/index.js
=> chore: Adds more bug tracking

src/Providers.js, src/ui/Onboarding/onboardingStatus.js
Fixes a navigation import issue.
Logout and log back in. Onboarding should skip to home tab correctly.
**Manual QA**
---
=> fix: Fixes Onboarding Getting Stuck

package.json, yarn.lock
This PR updates the core `ui-media-player` package that should have a fix in it for Chromecast.
I guess hook it up to a Chromecast and make sure it all works. 
**Manual QA**
---
=> chore: Update to new media player package

.github/workflows/detox.yml, ios/Podfile.lock, package.json
Adds e2e tests to our Github Actions flow
*NOTE: This will require us to upgrade to pods 1.9.3*
Wait for it to pass/fail
**Manual QA**
---
=> chore: Adds Detox to CI

src/tabs/connect/ActionBar.js, src/tabs/connect/ActionTable/index.js, src/tabs/connect/Connect.js
This PR makes some changes to the group link(s) on the Connect screen.
- It removes the "Manage your group" link from the link section on the bottom half of the screen.
- It changes the link to groups in the action bar:
- It will show "Join Group" and link to the groups page on the site (https://newspring.cc/groups) if you aren't a group leader.
- It will show "My Group" and link to the group leader hub page (https://newspring.cc/account/groups) if you are a leader.
First things first, make sure you are a group leader of a group.
Before pulling this branch, run the app from `master`, go to the Connect screen, and verify that you see the "Join Group" link in the action bar and the "Manage your group" link in the link section on the bottom.
Now pull the branch.
Run the app again and make …
=> chore: Update group link on Connect screen

src/client/index.js
=> fix: AppCenter error alert throwing error

CHANGELOG.md, android/app/build.gradle, ios/newspringchurchapp-tvOS/Info.plist, ios/newspringchurchapp-tvOSTests/Info.plist, ios/newspringchurchapp.xcodeproj/project.pbxproj, ios/newspringchurchapp/Info.plist, ios/newspringchurchappTests/Info.plist, package.json
=> chore: Bump to 7.9.1

src/tabs/home/Home.js, src/tabs/home/HomeSearchButton.js, src/tabs/home/__snapshots__/home.tests.js.snap
=> feat: Add SearchButton to the home feed

src/tabs/home/Home.js
=> feat: Adds Discover feed to Search
